baseURL = 'https://ziedbouraoui.github.io/gdr-radia-mhyia/'
languageCode = 'en-us'
title = 'GDR RADIA MHyIA'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-flex"

[menu]

  [[menu.nav]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.nav]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[[menu.nav]]
    identifier = "meetings"
    name = "Meetings"
    url = "/meetings/"
    weight = 10

[[menu.nav]]
    identifier = "members"
    name = "Members"
    url = "/members/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# membres
# meetings
# 
# description
# events
# participants
